{{- if .Values.model.deploy }}
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: {{ .Values.model.format }}
    opendatahub.io/model-type: generative
    openshift.io/display-name: {{ .Values.model.name }}
    security.opendatahub.io/enable-auth: {{ .Values.model.enableAuth | quote }}
    serving.kserve.io/deploymentMode: Standard
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: {{ .Values.model.genaiAsset | quote }}
    {{- include "playground.labels" . | nindent 4 }}
  name: {{ .Values.model.name }}
spec:
  predictor:
    maxReplicas: {{ .Values.model.replicas }}
    minReplicas: {{ .Values.model.replicas }}
    model:
      modelFormat:
        name: {{ .Values.model.format }}
      name: ""
      resources:
        {{- toYaml .Values.model.resources | nindent 8 }}
      runtime: {{ .Values.runtime.name }}
      storageUri: {{ .Values.model.storageUri }}
    {{- with .Values.model.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
